export interface LoanType {
  interest_rate?: any;
  id: string;
  name: string;
  group_id: string;
  is_active: boolean;
  last_update: number;
  additional_config: any;
  payment_option: string;
  contribution_type_id: string;
  can_go_next_year: boolean;
  description: string;
  duration_type: string;
  is_insured: boolean;
  insurance_percent: number;
  loan_formular: string;
  minimum_amount: number;
  maximum_amount: number;
  max_amount_balance_base: number;
  max_amount_type: string;
  max_duration_type: string;
  max_duration: number;
  min_duration: number;
  pay_same_amount_is_must: boolean;
  minimum_amount_for_reducing_required: boolean;
  minimum_amount_for_reducing_percent: number;
  profit_type: string;
  profit_percent: number;
  allow_loan_top_up: boolean;
  requires_guarantee: boolean;
  number_of_guarantee: string;
  textDescription?: string;
  is_fine_for_returns?:boolean;
  is_fine_for_completion?:boolean;
  fine_for_returns_calculation_type?:string;
  fine_for_returns_amount?:number;
  fine_for_returns_balance_factor?:number;
  fine_for_completion_calculation_type?:string;
  fine_for_completion_amount?:number;
  fine_for_completion_balance_factor?:number;

}
